/**
 * List of major SNCF train stations with their codes and names
 * The codes match the ones used in SNCF API
 */
const stations = [
  { code: 'FRPAR', name: 'Paris (toutes gares)' },
  { code: 'FRPMO', name: 'Paris Montparnasse' },
  { code: 'FRPST', name: 'Paris Est' },
  { code: 'FRPNO', name: 'Paris Nord' },
  { code: 'FRPLY', name: 'Paris Gare de Lyon' },
  { code: 'FRPAZ', name: 'Paris Austerlitz' },
  { code: 'FRPBE', name: 'Paris Bercy' },
  { code: 'FRLPD', name: 'Lyon Part Dieu' },
  { code: 'FRLPE', name: 'Lyon Perrache' },
  { code: 'FRLLE', name: 'Lille Europe' },
  { code: 'FRFLA', name: 'Lille Flandres' },
  { code: 'FRMSC', name: 'Marseille St Charles' },
  { code: 'FRTLS', name: 'Toulouse Matabiau' },
  { code: 'FRBOJ', name: 'Bordeaux St-Jean' },
  { code: 'FRMLW', name: 'Montpellier Saint-Roch' },
  { code: 'FRNTS', name: 'Nantes' },
  { code: 'FRNIC', name: 'Nice Ville' },
  { code: 'FRRNS', name: 'Rennes' },
  { code: 'FRRAJ', name: 'Strasbourg' },
  { code: 'FRADI', name: 'Aix-en-Provence TGV' },
  { code: 'FRAES', name: 'Avignon TGV' },
  { code: 'FRXBZ', name: 'Béziers' },
  { code: 'FRBES', name: 'Brest' },
  { code: 'FRCDN', name: 'Cannes' },
  { code: 'FRCK2', name: 'Châlons-en-Champagne' },
  { code: 'FRCMF', name: 'Chambéry - Challes-les-Eaux' },
  { code: 'FRCLQ', name: 'Clermont-Ferrand' },
  { code: 'FRDIJ', name: 'Dijon' },
  { code: 'FRGNB', name: 'Grenoble' },
  { code: 'FRLIL', name: 'Lille' },
  { code: 'FRLRT', name: 'Lorient' },
  { code: 'FRXMZ', name: 'Metz' },
  { code: 'FRMPL', name: 'Montpellier' },
  { code: 'FRMHK', name: 'Mulhouse' },
  { code: 'FRNCY', name: 'Nancy' },
  { code: 'FRNBO', name: 'Narbonne' },
  { code: 'FRPOP', name: 'Perpignan' },
  { code: 'FRRHE', name: 'Reims' },
  { code: 'FRDOL', name: 'Saint-Malo' },
  { code: 'FRSEE', name: 'Saint-Étienne Châteaucreux' },
  { code: 'FRTLN', name: 'Toulon' },
  { code: 'FRLAB', name: 'Valence TGV' },
  { code: 'FRAVY', name: 'Annecy' },
  { code: 'FRANK', name: 'Angers Saint-Laud' },
  { code: 'FRXAG', name: 'Angoulême' },
  { code: 'FRANG', name: 'Annemasse' },
  { code: 'FRXAA', name: 'Antibes' },
  { code: 'FRARY', name: 'Arcachon' },
  { code: 'FRARN', name: 'Arras' },
  { code: 'FRXAT', name: 'Auray' },
  { code: 'FRBVE', name: 'Beauvais' },
  { code: 'FRBIQ', name: 'Biarritz' },
  { code: 'FRBNF', name: 'Belfort' },
  { code: 'FRBIG', name: 'Bourg-en-Bresse' },
  { code: 'FRCAE', name: 'Caen' },
  { code: 'FRCCF', name: 'Carcassonne' },
  { code: 'FRCFE', name: 'Clermont-Ferrand' },
  { code: 'FRCOL', name: 'Colmar' },
  { code: 'FRKRI', name: 'Dax' },
  { code: 'FRXDR', name: 'Dunkerque' },
];

module.exports = stations;
